# Base image
FROM oven/bun:1

# Create app directory
WORKDIR /app

# Copy package files first (better cache)
COPY package*.json bun.lockb ./

# Install deps
RUN bun install --production

# Copy rest of the app
COPY . .

# Expose app port (change if needed)
EXPOSE 3000

# Start app
CMD ["bun", "run", "start"]
